# Generated by Django 4.2.4 on 2023-09-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_field"),
    ]

    operations = [
        migrations.RemoveField(model_name="field", name="field_type",),
        migrations.RemoveField(model_name="field", name="season",),
    ]
