# Generated by Django 4.2.4 on 2023-09-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_croprotation_crop_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="croprotation", name="season",),
        migrations.AddField(
            model_name="croprotation",
            name="season",
            field=models.ManyToManyField(related_name="Seasons", to="users.season"),
        ),
    ]
