# Generated by Django 4.2.4 on 2023-09-30 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_croprotation_season_croprotation_season"),
    ]

    operations = [
        migrations.RemoveField(model_name="croprotation", name="season",),
        migrations.AddField(
            model_name="croprotation",
            name="seasons",
            field=models.ManyToManyField(
                related_name="crop_rotations", to="users.season"
            ),
        ),
        migrations.AlterField(
            model_name="croprotation",
            name="crop_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="croprotation",
            name="crop_variety",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="croprotation",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crop_rotations",
                to="users.field",
            ),
        ),
        migrations.AlterField(
            model_name="croprotation",
            name="harvesting_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="croprotation",
            name="planting_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
