# Generated by Django 4.2.4 on 2023-10-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_farm_latitude_alter_farm_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="latitude",
            field=models.DecimalField(decimal_places=20, max_digits=35),
        ),
        migrations.AlterField(
            model_name="farm",
            name="longitude",
            field=models.DecimalField(decimal_places=20, max_digits=35),
        ),
    ]
