# Generated by Django 4.2.4 on 2023-10-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_field_field_crop_alter_field_field_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="field_crop",
            field=models.CharField(default="Crop", max_length=255),
        ),
        migrations.AlterField(
            model_name="field",
            name="field_name",
            field=models.CharField(default="Field", max_length=255),
        ),
    ]
