# Generated by Django 4.2.4 on 2023-10-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_field_field_crop_alter_field_field_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="season", name="fields",),
    ]
