# Generated by Django 4.2.4 on 2023-10-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_season_fields"),
    ]

    operations = [
        migrations.RemoveField(model_name="croprotation", name="seasons",),
        migrations.AddField(
            model_name="croprotation",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crop_rotations",
                to="users.season",
            ),
        ),
        migrations.AlterField(
            model_name="croprotation",
            name="crop_name",
            field=models.CharField(
                blank=True, default="Unknown Crop", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="croprotation",
            name="crop_variety",
            field=models.CharField(
                blank=True, default="Unknown Variety", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="croprotation",
            name="harvesting_date",
            field=models.DateField(blank=True, default="2000-01-02", null=True),
        ),
        migrations.AlterField(
            model_name="croprotation",
            name="planting_date",
            field=models.DateField(blank=True, default="2000-01-01", null=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="end_date",
            field=models.DateField(blank=True, default="2000-01-02", null=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="start_date",
            field=models.DateField(blank=True, default="2000-01-01", null=True),
        ),
    ]
