# Generated by Django 4.2.6 on 2023-10-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_croprotation_seasons_croprotation_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprotation',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_rotations', to='users.season'),
        ),
    ]
