# Generated by Django 4.2.6 on 2023-10-21 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_croprotation_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Incomplete', 'Incomplete')], default='Pending', max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.field')),
            ],
        ),
    ]
